scribble-lib/scribble/private/run-pdflatex.rkt
MacTeX, TeX for Mac, will install the binaries at `/Library/TeX/texbin`. Hence, we should add this path to the candidate-dirs.
=> Add /Library/TeX/texbin as another candidate-dir

scribble-doc/scribblings/scribble/manual.scrbl, scribble-lib/scribble/manual-struct.rkt, scribble-lib/scribble/private/manual-mod.rkt
Used to tell if a module implements a `#lang` or reader.
Required by https://github.com/racket/racket/pull/1355
=> Add language-index-desc struct, subtype of module-path-index-desc

scribble-lib/scribble/scribble.css
Code samples use `pre`, which will cascade into the margin note unless stopped.
Example of problem, reported by @mfelleisen:
=> fix text wrapping of margin notes within code samples

scribble-doc/scribblings/scribble/html.scrbl, scribble-html-lib/scribble/html.rkt, scribble-html-lib/scribble/html/extra.rkt, scribble-html-lib/scribble/html/html.rkt
(Successor to #39 and #56)
Provide renderers for html4 and html5 elements not exported by scribble/html, from modules:
- `scribble/html/4`
- `scribble/html/5`
`html/4` only provides `map`. Everything else is already in `scribble/html/html`. I guess we could move things from there to `html/4`, then require them in `scribble/html`.
`html/5` provides everything, including the ruby tags and `svg`. Using `only-in` or `prefix-in` to avoid name clashes shouldn't be too annoying.
=> update scribble/html tags, add scribble/html/extra

scribble-lib/scribble/manual-style.css
Fixes #66.
**BEFORE**
**AFTER**
**GOOD SIDE-EFFECT**
Before, if the page ended on a margin-note, it had no bottom margin:
Now, it has:
**CAVEAT**
To make this work, I had to remove the wiggle room on the margin note width. Before, it varied in size on the 1260–1340px viewport range. Now, it is fixed to always have its maximum width, which means that screens that previously would show narrower margin notes now show interspersed ones.
I don’t see a way to conciliate the two features, but it is a small price to pay for the benefit, in my opinion. Of course, you’re the ultimate judge 😀
**TESTED ON**
- Firefox 49.
- Chromium 51.
- Safari 10.
All on OS X El Capitan.
=> Fix margin notes overlap

scribble-lib/scribble/html-render.rkt
Forces the narrow (one-column) layout on mobile devices.
=> Add `meta` to Scribble template for mobile

scribble-doc/scribblings/scribble/xref.scrbl
This pull request fixes a typo in the contract, and updates the contract to reflect the description in the text.
=> Update documented contract for xref-binding->definition-tag

scribble-lib/scribble/base-render.rkt
Currently, if we run:
```
(traverse-block
(lambda (get set)
(lambda (get set)
(para (collect-element #f (bold (~a value))
(lambda (ci)
(collect-put! ci '(out some-value) value)))))))
```
The `value` will be successfully collected into `collect-info`. However, the code below would fail, without the collect lambda inside the `collect-element` being called.
```
(traverse-element
(lambda (get set)
(lambda (get set)
(collect-element #f (bold (~a value))
(lambda (ci)
(collect-put! ci '(out some-value) value))))))
```
This pull request handles `traverse-element` in `collect-content` to fix this.
=> Handle nested collect-element inside a traverse-element

scribble-lib/scribble/private/manual-proc.rkt, scribble-test/tests/scribble/docs/manual.scrbl
If a struct has no fields, don't check if a struct's name + first field's name
are too long to print on one line
Bug report: https://groups.google.com/forum/#!topic/racket-users/6fKGky4tud8
=> defstruct: no newline between name & fields if no fields

scribble-doc/scribblings/scribble/acmart.scrbl, scribble-lib/scribble/acmart.rkt, scribble-lib/scribble/acmart/lang.rkt
Just like the 10pt option in `scribble/sigplan`,
putting @9pt @10pt @11pt or @12pt on the #lang line of a `scribble/acmart`
document passes to corresponding string to `\documentclass[....]`
And just like TeX, it's ok to give multiple font sizes. All but the last are ignored.
(DLS for example want `sigplan` format and 10pt font. I added all the options because, why not.)
=> add font size options to scribble/acmart

scribble-doc/scribblings/scribble/acmart.scrbl, scribble-doc/scribblings/scribble/core.scrbl, scribble-lib/info.rkt, scribble-lib/scribble/acmart.rkt, scribble-lib/scribble/acmart/acmart.tex, scribble-lib/scribble/acmart/lang.rkt, scribble-lib/scribble/acmart/style.tex, scribble-lib/scribble/base.rkt, scribble-lib/scribble/latex-properties.rkt, scribble-lib/scribble/latex-render.rkt, scribble-lib/scribble/private/tag.rkt, scribble-lib/scribble/scribble.tex
Remove maketitle from scribble/acmart
This commit is the first that removes maketitle (and the need
for maketitle) in scribble/acmart. I want to get feedback before
I document and push.
(Also I would be willing to rename the `author` function to
`authorinfo`, to match the scribble/sigplan and existing
scribble/acmart packages.
=> Remove maketitle

scribble-doc/scribblings/scribble/core.scrbl, scribble-lib/scribble/acmart.rkt, scribble-lib/scribble/base-render.rkt, scribble-lib/scribble/latex-render.rkt
This allows us to raise nested flows above the title. So that we do
things like raise the abstract above the title:
```
\begin{abstract}
Abstract text
\end{abstract}
\titleCommand{...}
```
This style is required by the acmart style guide.
(Documentation will be in the next commit.)
=> Add a pretitle style property for nested flows.

scribble-lib/scribble/jfp/replacements.tex
Closes #103 .
I don't know why it's okay to use `xvpt` in `replacements.tex`, but this fix works for me on small documents and on the bigger example.
- - - 
Fixes an incompatibility between jfp1.cls and the 'relsize' package.
Justification for the fix:
1. `pdflatex` fails on this document
```
\documentclass{jfp1}
\begin{document}
\maketitle
hello {\Large world}
\end{document}
```
2. `pdflatex` succeeds on this document
```
\documentclass{jfp1}
\renewcommand\Large{\@setfontsize\@xvpt{18}}
\begin{document}
\maketitle
hello {\Large world}
\end{document}
```
I do not know why (1) fails.
=> patch for '\Large' in jfp1.cls

scribble-doc/scriblib/scribblings/autobib.scrbl, scribble-lib/info.rkt, scribble-lib/scriblib/autobib.rkt, scribble-test/tests/scriblib/autobib.rkt
These commands work like natbib's citeauthor and citeyear commands,
and facilities making possessive citations. For example:
Thanks to @(cite-author foo)'s (@(cite-year foo)) paper on stuff...
These identifiers are added with `define-cite` as keywords, and thus
can be omitted with no downside for backwards compatibility.
@(define-cite cite citet generate-bib
#:cite-author cite-author
#:cite-year cite-year)
=> Add commands for cite-author and cite-year to autobib.

scribble-lib/scriblib/bibtex.rkt
Handles comma-separated Last,First and Last,Jr,First format for names in bibtex, as well as `von`, `de la` and `van der` separators.
Note that this patch does not add support for disambiguating braces as bibtex normally supports, e.g. `{first fst} {last lst}`. That would require a more involved parser.
=> Last,First format for names in bibtex

scribble-doc/scribblings/scribble/base.scrbl
@mflatt thanks for the help on slack, `#:style 'block` does produce a LaTeX `tabular`
I think this PR fixes a typo.
If it's not a typo, I'll change it to a "see also". Because the docs for `para` didn't help me understand `tabular`'s `#:style`
(If I had the list of styles from `table`'s docs, I could have at least tried those to see what happened.)
=> doc: point 'tabular #:style' to 'table' docs

scribble-lib/scribble/acmart/style.tex
cc @LeifAndersen 
Change implementation of `@title` to just use `\title`.
Do not try to extract a subtitle from the argument.
This fixes a bug, where the `Title` meta-data in the PDF for a document titled
"Foo" was "oo" (same title with first letter missing). So, e.g., Google chrome
would show "oo" as the tab title for the document.
- - -
Why remove the `\let` altogether?
1. I don't think we need it in `scribble/acmart`, because there's a separate `@subtitle` command
2. Keeping it generates two warnings when running LaTeX:
```
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\<let>-command' on input line 674.
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing …
```
=> acmart: remove subtitle extraction

scribble-lib/scribble/example.rkt, scribble-test/tests/scribble/example.rkt
Add contracts to `scribble/example` exports, and tests to make sure negative blame gets assigned as expected.
Closes #117
=> add contracts to scribble/example

scribble-doc/scribblings/scribble/examples.scrbl
Change the documented order of arguments to match the implementation / uses in `scribble/eval.rkt` and `scriblib/gui-eval.rkt`.
- - -
Alternatively, we could change the implementation to match the docs.
- on one hand, I think making the "catch exceptions?" flag the 3rd argument is easier to explain & remember
- on the other hand, it's a larger change and will make calls to `(scribble-eval-handler)` a little more awkward-looking (`((scribble-eval-handler) ev (.... large term to eval ....) #f)`)
Just changing the docs is my preference, and if nobody speaks up I'll just merge this in a few days.
=> doc: fix 'scribble-eval-handler' order of arguments

scribble-doc/scribblings/scribble/acmart.scrbl, scribble-lib/scribble/acmart.rkt, scribble-lib/scribble/acmart/lang.rkt
1. Change `add-acmart-styles` to add an element WITHOUT the `pretitle` style
for the collects phase. With this, an empty `#lang scribble/acmart` document
builds an empty PDF.
2. Add documentation for a "minimal" `scribble/acmart` document.
re #121 : This PR doesn't add a helpful error/warning message, but at least it's the same behavior now as `scribble/sigplan`.
=> acmart: a little better for empty documents

scribble-lib/scribble/acmart.rkt, scribble-lib/scriblib/bibtex.rkt
- Add support for PhD bib entries in scriblib/bibtex
- Use exact chars in acmart badge commands to avoid escaping URL characters
=> Small improvements for scriblib/bibtex and acmart

scribble-lib/scribble/acmart/acmart-load.tex, scribble-lib/scribble/acmart/acmart.cls
Closes #125 
Stop using the `tocstyle` package; `acmart.cls` makes a good table of contents without it.
=> acmart: fix table-of-contents

scribble-lib/scribble/acmart.rkt
The ccsdesc function was defined, but not provided.  Also added use of
exact-chars since its argument contains characters such as "~" which
should not be converted to \sim.
=> Provide ccsdesc, use exact-chars.

scribble-lib/scriblib/autobib.rkt, scribble-test/tests/scriblib/autobib.rkt
Fixes capitalization when `book-location` edition is an ordinal.
Eg, the following file:
```
#lang scribble/base
@(require scriblib/autobib)
@(define htdp
(make-bib #:title "HTDP"
#:author "MRMS"
#:is-book? #t
#:location (book-location #:edition "1st" #:publisher "MIT")
#:date "2001"))
@(define-cite cite citet gen-bib)
@cite[htdp]
@(gen-bib)
```
capitalizes the edition incorrectly:
```
(MRMS 2001)
Bibliography
MRMS. HTDP. 1St edition. MIT, 2001.
```
=> autobib book-location: fix capitalization of ordinal editions

scribble-doc/scribblings/scribble/examples.scrbl
Also increase the memory limit in the example.
(On my machine, this example fails if the memory limit is 37MB or less.)
Closes #137
=> doc: require 'scribble/example' in 'examples' example

scribble-doc/scribblings/scribble/acmart.scrbl, scribble-lib/scribble/acmart.rkt, scribble-lib/scribble/acmart/acmart-load.tex
The first commit makes the acmart style file disable the default Scribble redefinition of `\rmdefault`, since that plays badly with acmart. I'm pretty sure @LeifAndersen had the same problem, but I don't know how she fixed it.
The second one make `grantsponsor` and `grantnum` work. I think the old versions may have been a cut-and-paste error that kept too much from a related function.
The third commit is in the same vein, but for some other functions and more a question of generalizing contracts than making things work at all.
=> acmart fixes

scribble-doc/scribblings/scribble/acmart.scrbl, scribble-lib/scribble/acmart.rkt
This was added in a recent version of the acmart style and is
required to set (or remove) the addresses field at the bottom of
the first page in some styles.
=> Add authorsaddresses field.

scribble-lib/scribble/acmart.rkt
The docs claimed it was there, but we missed it when creating
scribble/acmart. As such, this commit adds it in.
=> Add include-abstract.

scribble-lib/scribble/scribble.tex
add `\phantomsection`s to make valid hyperref targets
(just like #142 )
=> scribble.tex: add phantomsection to TOC links

scribble-doc/scribblings/scribble/lp.scrbl, scribble-doc/scribblings/scribble/manual.scrbl
EDIT resolved
~Is it possible (without using `verbatim`) to make the `racketblock` render exactly as:~
```
@include-section[(submod "file.scrbl" doc)]
```
Screenshots:
=> doc: example include-section for scribble/lp2

scribble-text-lib/scribble/text/output.rkt
Specials are used to represent entities such as nbsp, so the predicate special? needs to be exported
for users of scribble/text to recognize such elements. It is no longer possible to use the contract - since
the contract has effectively been bypassed.
=> Provide special? from scribble/text/output

scribble-lib/help/search.rkt
Currently, `raco docs` will open a web browser to a "file not found" page when docs are not installed and `doc-open-url` is not set in `config.rktd`.  This can be an issue for linux distributions which package the docs separately from racket itself, because modifying `config.rktd` dynamically as part of the install process could overwrite a user's preference.
This PR fixes the issue by pointing `send-main-page` to "https://docs.racket-lang.org/" when docs can not be found.
=> point send-main-page to racket website when docs not found

scribble-lib/scribble/scribble-common.js
The Racket docs are extremely helpful and useful while programming, and are some of the highest quality documentation I've worked with. I spend a lot of time scanning pages of documentation when programming in Racket.
One thing that would be helpful, is a hotkey that focuses on the "... search manuals ..." text field. For instance, Rust's generated documentation allows you to press S to focus on the search bar ([screenshot](https://0x0.st/5WL.png)). I, and others who have a primarily keyboard-oriented workflow, would appreciate a similar feature.
In this PR I have implemented the same functionality: pressing S focuses to the search bar.
=> pressing "S" on the page body focuses to the search box

scribble-doc/scribblings/scribble/manual.scrbl, scribble-lib/scribble/private/manual-bib.rkt
Add an optional argument to bib-entry to typeset a comment directly
after a citation --- with no punctuation between the end of the citation
and start of the comment.
Example uses:
- making an annotated bibliography, with an element that appears just
below each citation
- adding "accessed" dates just after a URL, e.g.
`(bib-entry .... #:url "...." #:note ", accessed 2018-06-14")`
Example document:
```
#lang scribble/manual
@title{Doc}
@(bibliography
(bib-entry #:key "WT18"
#:author "J. Wang and S. Z. Taylor"
#:title "Parabolic Monoids and Concrete Galois Theory"
#:location "Mathgen"
#:date "2018"
#:url "http://thatsmathematics.com/mathgen/"
#:note ", accessed 2018-06-14")
(bib-entry #:key "RJ18"
#:author "D. Raman and R. A. Jones"
#:title "On the Computation of Equations"
#:location …
```
=> add optional #:note to 'bib-entry'

scribble-doc/scribblings/scribble/acmart.scrbl, scribble-lib/scribble/acmart.rkt
Add the `email-string` function that
- Takes only `string?`s
- Escapes `%` and `#` (as discussed in #185)
- Typeset the email address using `exact-chars`
- Produce the result as a `email?`.
=> Add email-string to typeset email with exact-chars

scribble-doc/scribblings/scribble/acmart.scrbl, scribble-lib/scribble/acmart.rkt
The `#:email` argument in `author` takes `(or/c pre-content? email? (listof email?) #f)` instead of `(or/c pre-content? (listof pre-content?))`. This also seems to be the case in the code. Plus, all `(listof pre-content?)` values are already a `pre-content?`.
=> Synchronize the document of #:email in author with its actual the contract

scribble-lib/scribble/html-render.rkt
when rendering multiple html files to a directory `d`, add
`d/index.html` to the set of files-to-be-writted to avoid overwriting
the main index with a part that happens to have the same tag
fixes #194
=> htmls: don't overwrite index.html

scribble-doc/scribblings/scribble/manual.scrbl
I think something should be said about what `block?` does but I am not comfortable enough with the scribble code to write it down.
=> Add block? contract to typeset-code

scribble-doc/scribblings/scribble/how-to-paper.scrbl
Chagne the Getting Started guide to suggest `scribble/acmart` instead of
`scribble/sigplan` for a PL workshop paper.
=> doc: use 'scribble/acmart' as Getting Started example

scribble-lib/scribble/scribble-common.js
1. Focus on the search box for either "s" or "S"
... accepting only "s" makes sense to me, but the comment said it
accepted "S" and well why not
2. Look for a "keyup" event instead of key press, so that pressing "s"
ONLY focuses on the box and does not focus-and-write-the-letter-"s"
"keyup" events apparently don't have a useful `charCode` field so this
PR looks at the `keyCode` field instead
cc @iitalics
=> search box: change '"s" for search' behavior

scribble-doc/scribblings/scribble/srcdoc.scrbl
I couldn't locate gif.rkt in the `file' collection. Seeing a complete working example was helpful to get started. I think it will be as useful for other Racketeers (especially beginners like myself).
If gif.rkt is indeed gone due to refactorings, I guess the reference to it should be removed.
=> Add https://blog.racket-lang.org/2012/06/submodules.html as an example for in-source documentation

scribble-lib/scribble/srcdoc.rkt
As discussed on racket-users@, thing-doc provide form raises misleading message if id is not an identifier.
=> Fix raised exception on erroneous thing-doc usage.

scribble-doc/scribblings/scribble/srcdoc.scrbl, scribble-lib/info.rkt, scribble-lib/scribble/srcdoc.rkt
There should probably be @history[#:added ...] added to both scribblings.
=> scribble/srcdoc: add `class*-doc` and `class-doc` provide forms

scribble-lib/scribble/bnf.rkt, scribble-lib/scribble/comment-reader.rkt, scribble-lib/scribble/config.rkt, scribble-lib/scribble/racket.rkt, scribble-lib/scribble/search.rkt
This pull request cleans up files using the file-level `(module ...)` mechanism to instead use `#lang`. Then the files were reindented using DrRacket's default indenting preferences.
=> Langify scribble modules

scribble-doc/scribblings/scribble/base.scrbl, scribble-lib/scribble/base.rkt, scribble-lib/scribble/html-render.rkt, scribble-lib/scribble/latex-render.rkt, scribble-lib/scribble/markdown-render.rkt, scribble-lib/scribble/scribble.css
Use \emph in the LaTeX renderer and CSS in the HTML renderer to make nested emphasis toggle between italics and upright.
The CSS for this is not very nice (the nesting is written out); it would be nicer if the proposed "toggle()" function were available.
Also, it would seem sensible to use `em` elements in HTML, but I can't work out how to generate those at the point where styles are dealt with.
=> Make @emph nestable, logical markup

scribble-doc/scriblib/scribblings/autobib.scrbl, scribble-lib/scriblib/autobib.rkt, scribble-test/tests/scriblib/autobib.rkt
- fix #216 by coercing author-element data to a string, add tests
- doc edits:
- import `scribble/core` to fix link to `content?`
- fix typo in `dissertation-location`
- replace unbound reference to `name/c` with a real contract
=> autobib: fix author formatting (#216)

scribble-doc/scribblings/scribble/manual.scrbl, scribble-lib/scribble/private/manual-style.rkt
`exec` and `commandline` are documented as decoding their content, and they have contracts that suggest that they do, but in fact they do not. Whether originally intentional or not, this corrects the documentation and contracts to match their true behavior.
=> Fix the contracts on `exec`/`commandline` to match their behavior

scribble-lib/scribble/private/manual-code.rkt
=> Provide a distinguished source when reading in `codeblock`.

scribble-lib/scribble/manual-racket.js
Automatically link to source code of document.
This works, provided that:
- the package is on the catalog at pkgs.racket-lang.org
- the package is hosted on GitHub
- the package source does not specify a branch
Restriction 3 is easy to lift with more parsing.
Restriction 2 could be lifted for other known sites (such as gitlab)
or packages hosted as directories.
Restriction 1 would be harder to lift.
This only links to the _top level_ file that defines the overall
document, not the file defining the particular section. Fixing that
would require the Scribble renderer to provide more detailed
information, although it's certainly a possible extension.
Currently, some single-collection packages get the wrong answer,
but that will change when racket/pkg-index#25 finishes updating on
the server. …
=> Automatically link to source code of document.

scribble-doc/scribblings/scribble/core.scrbl, scribble-lib/info.rkt, scribble-lib/scribble/html-properties.rkt, scribble-lib/scribble/html-render.rkt
Closes #231. This pull request only touches the HTML rendering implementation code; it has no tests and does not yet update the docs. I'd like to get some feedback on whether this is the right implementation approach before getting to tests and docs.
=> Implement support for converting values to GIFs

scribble-doc/scribblings/scribble/manual.scrbl, scribble-lib/info.rkt, scribble-lib/scribble/private/manual-class.rkt
- Raise a syntax error when bogus mode arguments are given.
Note that https://github.com/racket/gui/pull/193 must be merged first.
- Fix a bug where `extend-final`, `augment-final`, and `public-final` are not recognized
- Document the `public` mode which was already supported but not
documented.
- Clarify the default mode when `maybe-mode` is not given.
=> Fix #131: disallow bogus mode arguments and fix related bugs

scribble-lib/scribble/html-render.rkt
Repairs a problem with #232.
Relevant to racket/racket#3300.
Should be merged to the release. 
@jbclements @jackfirth
=> Convert GIF size to string.

scribble-lib/scribble/acmart/acmart-load.tex
Commit c62d008cf include txfonts into the set of
default LaTeX packages. However, txfonts changes
the main font of the document, conflicting the
requirement of `scribble/acmart` articles.
We skip txfonts by setting `packageTxfonts` to nop.
Closes #271.
=> Disable txfonts package in scribble/acmart

scribble-doc/scribblings/scribble/config.scrbl, scribble-lib/info.rkt, scribble-lib/scribble/scribble-load.tex, scribble-lib/scribble/scribble.tex
Replace txfonts with newtxmath.
- The newtx package supersedes txfonts.
- As a side effect, we have to load amsmath
as well and it has to be loaded before
mathabx and wasysym.
- Add nointegrals option to wasysym to avoid conflicting amsmath.
- Pick the \widering from newtxmath over the \widering from mathabx.
For now, I have tried rendering PDFs for all languages but `scribble/jfp` in [High-Level Scribble API](https://docs.racket-lang.org/scribble/generic-prose.html) on the scribble files here: [scribble-langs-client.zip](https://github.com/racket/scribble/files/5248862/scribble-langs-client.zip).
The newtx package provides quite some [options](http://texdoc.net/texmf-dist/doc/fonts/newtx/newtxdoc.pdf) for selecting different styles of math symbols (e.g. `libertine`, `upint` or …
=> Replace txfonts by txmath

scribble-lib/scribble/scribble-common.js
In non QWERTY keyboard, pressing S won't focus the search bar.
This PR fixes the problem.
Note that `keyCode` is not supported in IE8 already, so the fact
that `key` is not supported in IE8 too doesn't really matter:
the PR doesn't cause browser compatibility for the features to degrade.
=> Use key instead of keyCode

scribble-lib/scribble/html-render.rkt, scribble-lib/scribble/scribble.css
HTML supports the placeholder attribute, so we should use it
instead of implementing it ourselves.
The placeholder attribute is not available prior IE10 (not including
IE10). However:
1. In non-supporting browsers (e.g., IE9), the search functionality
should still work correctly.
2. Non-supporting browsers don't qualify for the "full support" level
detailed in https://github.com/racket/scribble/pull/240/
IE9 for instance is released in 2011, and Microsoft announced its end of
support in 2016.
Also, technically this is a bug fix. Currently, if users type `...search manuals...` as a search query, focus somewhere else, and then focus the search box again, the text will disappear.
=> Refactor search placeholder

scribble-lib/scribble/lncs/lang.rkt, scribble-lib/scribble/lncs/lncs-load.tex
Block scribble from changing the default font to ptm for LNCS articles. Unfortunately, the math fonts are still incorrectly altered by newtxmath and I don't see a way to work around it.
Depends on #274.
=> Block scribble from changing the font to ptm in LNCS

scribble-lib/scribble/html-render.rkt, scribble-lib/scribble/scribble-common.js
When the search box is not present (e.g.,
https://docs.racket-lang.org/demo-m1/index.html),
pressing "S" will result in a JS error. This PR fixes the problem.
Note that semantically it makes more sense to give an ID to the
search box as we know exactly what search box we want.
=> Fix JS error when searchbox is not present

scribble-doc/scribblings/scribble/manual.scrbl, scribble-lib/scribble/private/manual-form.rkt, scribble-lib/scribble/private/manual-history.rkt, scribble-lib/scribble/private/manual-proc.rkt, scribble-lib/scribble/private/manual-vars.rkt
Forms like `deftogether` and `defproc*` currently allow empty spec,
causing an empty box to be rendered. These malformed outputs are better
prevented at compile-time.
`defform*` already disallows empty spec, but the error is reported
in terms of `defform*/subs`, so this PR adjusts it to directly error
in terms of `defform*`. `defsubform*` still unfortunately errors
in terms of `defform*`, but the fix is too invasive to be worth it.
This PR is tested against all docs in the main distribution.
There's no error.
=> documenting forms: disallow empty box

scribble-lib/scribble/search.rkt
This pull request was generated by an automated tool, with some by-hand postprocessing to preserve comments. The tool replaces uses of the various `let` forms with equivalent `define` forms, when doing so would reduce nesting and when it can prove that the binding structure remains unchanged. Parts of this change involved changing some code from using `if` to using `cond`, as well as other similar changes needed to introduce a definition context.
The tool produces moderately well-formatted code, but it makes a conscious effort to avoid changing the formatting of any existing subforms that were not refactored.
Note: the tool is called `resyntax`, and is implemented [here](https://github.com/jackfirth/resyntax).
=> Replace let forms with definitions in scribble/search

.github/workflows/ci.yml
Based on the [Typed Racket CI config](https://github.com/racket/typed-racket/blob/master/.github/workflows/ci.yml). No idea if this works, since I don't have a way to test it.
=> Attempt to add CI for scribble packages

scribble-lib/scribble/manual-style.css
This helps with navigation of long docs pages. For an example, see:
https://www.students.cs.ubc.ca/~cs-411/docs/reference/sets.html?q=sets
=> Make navbar stick and scrollable

scribble-lib/scribble/manual-style.css
This ensures that the scroll bar starts in the appropriate place, and the
background of the border is appropriate when the navtopset is missing
Fixes the issue @rfindler found in #297 after the merge.
=> Fix some overflows issues caused by the sticky navigation bar

scribble-lib/scribble/base.rkt
Both these functions allow the `#:doc` argument to be `#f`, and in fact that is the default value, but their contracts are overly strict, so passing it explicitly triggers a contract violation. This commit therefore weakens the contracts to allow `#f`, as they should.
=> Fix contracts on Secref and seclink

scribble-text-lib/scribble/text/syntax-utils.rkt
This should be merged when https://github.com/racket/racket/pull/3927 is.
=> Fix to match definition context hygiene change

scribble-text-lib/info.rkt
The change in https://github.com/racket/scribble/commit/b149a17c3bb4fbfacd63e1c72d811a215741188c
depends on the expanded API of `syntax-local-identifier-as-binding` in https://github.com/racket/racket/commit/816c26482c414ed7a244bc25d0ba9749a6290e0b
=> add minimum version dependency to scribble-text-lib

scribble-lib/scribble/html-render.rkt, scribble-lib/scribble/manual-style.css, scribble-lib/scribble/scribble-common.js, scribble-lib/scribble/scribble.css
This adds a button to show / hide the TOC column on low-width devices.
It also adjusts various styles to keep the top bar fixed as you scroll so that the TOC toggle button remains accessible anywhere in the document. Flexbox is used in the low-width nav bars to improve vertical centering.
The appearance on high-width devices is unchanged. No TOC button is shown there.
https://user-images.githubusercontent.com/279572/132976575-bc61329e-c1fc-4cb1-a936-4fd9bbcd869d.mov
Fixes https://github.com/racket/scribble/issues/313
Also fixes https://github.com/racket/scribble/issues/305
=> Add table of contents toggle for low-width devices

scribble-lib/scribble/scribble-load.tex
`newtxmath` has added `\widbar` since the version 1.7.0. The latest version of `newtxmath` is included in TeXLive 2022, which was just released in April.
=> use \widebar from newtxmath

scribble-lib/scribble/manual-racket.css, scribble-lib/scribble/racket.css
Whitespaces should be preserved in `litchar`
Before the PR (on page https://docs.racket-lang.org/drracket/Keyboard_Shortcuts.html): 
After the PR:
=> Add "white-space: pre" to RktIn

scribble-lib/scribble/scribble-common.js
Tools like Racket Mode could open a search page with an incorrectly encoded search query. While this is obviously the tools' fault, Scribble should be able to recover from the malformed input and not totally cease to function. This PR fixes the issue.
=> search: handle URIError on decodeURIComponent

scribble-lib/scribble/text-render.rkt, scribble-test/tests/scribble/docs/linebreak.scrbl, scribble-test/tests/scribble/docs/linebreak.txt
Here's an attempt at an implementation, tested so far only on my current draft of https://github.com/racket/racket/pull/4301.
Related to https://github.com/racket/racket/pull/4301
Closes https://github.com/racket/scribble/issues/333
=> scribble/text-render: support `(linebreak)`

scribble-doc/scribblings/scribble/core.scrbl, scribble-doc/scribblings/scribble/manual.scrbl, scribble-lib/info.rkt, scribble-lib/scribble/private/manual-tech.rkt
These seem to do the right thing, but the links they generate for https://github.com/racket/racket/pull/4301 don't redirect successfully, and I don't understand why. So, this probably isn't ready to merge yet.
=> add `#:indirect?` argument for `tech` and `techlink`

.github/workflows/resyntax-analyze.yml, .github/workflows/resyntax-submit-review.yml
This sets up Resyntax analysis on pull requests to this repository. Resyntax will analyze changed files and submit a review of the pull request containing its suggested changes. See [here](https://github.com/racket/typed-racket/pull/1277) for an example.
The workflows are a copy of the workflows I made for Typed Racket. In the future we can make these workflows reusable so they don't have to be copied into every repository, but one step at a time.
=> Add Resyntax integration

scribble-lib/scribble/base.rkt
I tried to rebuild the style from the style of `le` as was done previously, but this ran into contract errors that seem to suggest the contract is wrong, so I did this instead.
Is the contract on `make-style` actually accounting for this style property?
closes #348
=> Actually use link-render-style in Secref

scribble-lib/scribble/private/manual-form.rkt, scribble-lib/scribble/private/manual-proc.rkt
The following program:
```
@defform[(stream elem-expr ...)
#:literals (values)
#:grammar ([elem-expr (values single-expr ...)
single-expr])]{
Description ...
}
```
is faulty because `#:literals (values)` is misplaced. It should come before `(stream elem-expr ...)`.
However, the error that occurs is very confusing.
elem-expr: misuse of an identifier (not in `racket', etc.) that is bound as a code-typesetting variable
When parsing the form, `#:literals ... #:grammar ...` becomes a part of the description because there is no constraint that the description must not be keywords.
The resulting expansion is `(list #:literals .... #:grammar <grammar> ....)`, which happens to be valid, though `<grammar>` is not meant to be an expression. This is the cause of the mentioned confusing error message. …
=> Add constraints that descriptions must be non-keyword

scribble-lib/scribble/latex-render.rkt
guillemetleft for `«`, and guillemetright for `»`.
See also https://github.com/racket/gui/pull/297
=> tex-table: add guillemetleft and guillemetright

.github/workflows/ci.yml
- Bump the version of `Bogdanp/setup-racket` to fix the CI failure
- Modernize local catalog setup in the workflow using the `local_catalogs:` feature introduced in setup-racket v1.2
=> Update the workflow to account for CI failures

scribble-lib/scribble/html-render.rkt, scribble-lib/scribble/manual-racket.js, scribble-lib/scribble/manual-style.css
This commit adds two buttons to each heading title.
These buttons are by default hidden, but they will
appear on hovering on the heading titles.
The first button is a "link here" button, which adjusts the URL of the
current page to include an anchor to link to that heading title, similar
to how GitHub makes each heading title in README documents a link
to add an anchor.
The second button is to view Scribble source and internal link.
Previously, clicking heading titles serves this functionality,
but without an indicator that heading titles can be clicked,
the feature is not discoverable. So this commit makes a
transition toward an explicit button.
Example screenshots:
Page title
Section title
=> feat: add explicit buttons to heading titles

scribble-lib/scribble/scribble-common.js
Browsers released within the last 5 years (the partial support tier according to https://github.com/racket/scribble/pull/240) support URLSearchParams, so we should use it.
=> refactor: modernize JS in scribble-common.js

scribble-lib/scribble/html-render.rkt, scribble-lib/scribble/manual-style.css, scribble-lib/scribble/scribble.css
This PR fixes a couple of issues related to the button group.
- On `#lang scribble/base`, only show the "Link to here" button,
and do so with correct styling.
- Make it possible for the button group to exceed the right margin
to preserve the previous HTML layout.
- Place anchor at the beginning of the headings, not at the end,
so that on navigation, we will see the full heading.
Thanks to @mflatt who reported some of the issues above and
helped with testing.
Fixes https://github.com/racket/scribble/issues/381
=> html renderer: correct the button group 

scribble-doc/scribblings/scribble/manual.scrbl, scribble-lib/scribble/racket.rkt
- `code:contract#` only allows one subform in the implementation, but the documentation allows many subforms.
- `code:quote` only allows one subform in the documentation, but the implementation allows many subforms.
This PR corrects both the implementation and the documentation so that the implementation and the documentation agree with each other.
=> typeset: correct the form of `code:contract#` and `code:quote`

scribble-doc/scribblings/scribble/manual.scrbl, scribble-lib/scribble/private/manual-proc.rkt, scribble-lib/scribble/private/marshal.rkt, scribble-test/tests/scribble/docs/manual-ex.rkt, scribble-test/tests/scribble/docs/manual.scrbl, scribble-test/tests/scribble/docs/manual.txt
Manually specifying `#:value` could be cumbersome. An example is `html-empty-tags` from the `xml` collection, which is a list of more than 10 symbols.
It is also error-prone, and could be out-of-sync from the actual value.
This PR adds a support for `#:auto-value` in `defparam` and `defthing` to automatically query the value from the `for-label` binding.
Thanks to @LiberalArtist for the help in https://github.com/racket/racket/pull/4807.
=> feat: support #:auto-value for defparam and defthing

scribble-doc/scribblings/scribble/manual.scrbl, scribble-lib/scribble/private/manual-proc.rkt, scribble-test/tests/scribble/docs/manual-ex.rkt, scribble-test/tests/scribble/docs/manual.scrbl, scribble-test/tests/scribble/docs/manual.txt
The `defstruct[*]` form does support field options. Therefore use the same grammar as [`[define-]struct`](https://docs.racket-lang.org/reference/define-struct.html#%28form._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._struct%29%29) in the documentation.
=> Refine the grammar of `field-name` in `defstruct`.

scribble-lib/scribble/racket.rkt
This PR consists of two parts: semi-automatic fixes by Resyntax, and manual fixes.
Resyntax fixes are commits with the prefix `resyntax:`. Each commit corresponds to fixes due to a rule. The methodology to produce fixes is as follows:
1. Run Resyntax, and pick "the first fix".
2. Apply all fixes with the same rule as "the first fix". 
3. Re-run Resyntax again to possibly get more fixes, and go to step 3 until we reach the fixed point.
Resyntax is modified to omit some rules that are not suitable for the file, but it is also made more lenient in presence of comments (https://github.com/jackfirth/resyntax/issues/232), making it possible to discover fixes that the standard Resyntax can't discover.
=> Refactor racket.rkt

scribble-doc/scribblings/scribble/manual.scrbl
`[pre-content any/c]` -> `[pre-content pre-content?]`
=> Clarify contract for `pre-content` in `link`.

scribble-lib/scribble/acmart.rkt, scribble-lib/scribble/acmart/lang.rkt, scribble-lib/scribble/comment-reader.rkt, scribble-lib/scribble/contract-render.rkt
Similar to #432, this pull request runs Resyntax on various files. Each commit is a single pass from Resyntax, and the commit message lists the refactoring rules that were applied.
=> Run Resyntax on various files

scribble-lib/scribble/base-render.rkt
Similar to #432, this pull request runs Resyntax on the `scribble/base-render` module. Each commit is a single pass from Resyntax, and the commit message lists the refactoring rules that were applied.
=> Run Resyntax on `scribble/base-render`

.github/workflows/resyntax-autofixer.yml
Specifically:
- Use the Resyntax CI bot account, to ensure status checks are run on the autofixer pull requests. (Automated pull requests created with the normal GitHub Actions account aren't allowed to trigger other action runs, to prevent accidental recursion.)
- Limit the number of modified files to 3, so that Resyntax focuses on fully refactoring a few files instead of partially refactoring many files.
- Increase the limit on the number of fixes applied from 10 to 20, to give Resyntax a better shot at running multiple passes on the modified files.
=> Tweak Resyntax Autofixer workflow

scribble-doc/scribblings/scribble/core.scrbl, scribble-doc/scribblings/scribble/manual.scrbl, scribble-lib/info.rkt, scribble-lib/scribble/base.rkt, scribble-lib/scribble/core.rkt, scribble-lib/scribble/manual-struct.rkt, scribble-lib/scribble/private/manual-bind.rkt, scribble-lib/scribble/private/manual-class.rkt, scribble-lib/scribble/private/manual-form.rkt, scribble-lib/scribble/private/manual-proc.rkt
This is a revised version of #328
The `exported-index-desc*` struct adds an `extras` field that is a composable catch-all for extensions. The set of keys in `extras` is meant to be a mixture of well-known keys and third-party keys that a producer and consumer might agree on; the contract on `exported-index-desc*` checks that well-known keys have values of the right shape.
The initial well-known keys are `'kind` (corresponding to the text in the upper right of a documentation box), `'hidden?` (indicates an entry that looks redundant to a user, so it should be filtered out when rendering), `'method`, `'constructor?`, and `class-tag`. Those last 3 cover the information that used to be provided by `method-index-desc` and `constructor-index-desc`.
For a method, the index text now includes …
=> Add `exported-index-desc*`

scribble-lib/scribble/scribble-common.js
Fixes #454. The other half of this PR is at https://github.com/racket/racket/pull/5095.
This PR specifically removes `page_query_string` and `page_args`, which updates on each page refresh, and is in favor of `GetPageQueryString` and `GetPageArgs` function calls to fetch the current URL and its params.
=> Update URL query param upon completed searches

scribble-doc/scribblings/scribble/core.scrbl, scribble-doc/scribblings/scribble/renderer.scrbl
When I read the documentation, I found two typos.
=> fixed some typos in the doc

scribble-lib/scribble/acmart/acmart.cls
This version of acmart changes its dependencies are the latex level. I built a recent paper and nothing seemed to change, but I don't know much about the specifics of the dependencies so I'm opening a pull request here in case anyone wants to try anything out before this is merged.
=> update acmart to v2.12

scribble-lib/scribble/html-render.rkt
Each author is a paragraph. Block elements are not allowed within an inline element. Change the span to a div.
=> replace SAuthorList span with div

scribble-lib/scribble/scribble-prefix.html
The dtd spec is a hold over from long retired standards; moreover scribble renders HTML that doesn't adhere to the dtd specified here (e.g. <section>).  This change follows the HTML "Living Standard": https://html.spec.whatwg.org/multipage/syntax.html#syntax-doctype
=> Update scribble-prefix.html for modern standards
